print("Welcome to the bad name generator")
city=input("What's the name of the city you grew up in?\n")
print(city)
pet=input("what's your pet's name\n" )
print(pet)
print("Your band name could be "+ city+" "+pet )